### PR TITLE
Feature unused files

### PR DESCRIPTION
**Pull request by noisyjerm**
Adds an extra column in the table to show if files embedded in labels and course summaries are actually used.

### CODE REVIEW

**Comment by larsbonczek** [comment]
Thank you for your contribution. It looks like a great improvement!

There are just a few things that I noticed, which I think require some extra work:
- Properties in course_file class should not be dynamically declared
- Missing localization in templates/view.mustache:95 (German translation: "Verwendet")
- Incorrect localization in lang/de/local_listcoursefiles.php:58 (German translation: "Nicht überprüft"). By the way: Why does it say "Not tested" rather than "Unknown"?
- Missing return in course_file::get_file_download_url
- Why should course_file::get_edit_url ever return a string? Wouldn't moodle_url or null do the trick?

If you take care of these issues, we'll be happy to merge this.

**Review by larsbonczek — CHANGES_REQUESTED** [review]
see above

**Comment by noisyjerm** [comment]
Thanks for your review and feedback, I have made the changes you recommended. 
The reason I used the words "Not tested" rather than "Unknown" is that I feel from a technical perspective that it is more accurate to say we didn't check to see if this file is used or not. But from a non-technical end-user perspective, "Unknown" might be a better choice of words. I am happy to change the wording if you would like.

Note, I changed the property names as the code checker stated that underscores are not allowed in member variables. The guidelines referred to are a little vague on this however: https://docs.moodle.org/dev/Coding_style#Naming_Conventions. It affected the template as well.

**Review by larsbonczek — APPROVED** [review]
Thanks!

**Pull request merged**
